### ISSUE TITLE
Update postlove extension

### ISSUE THREAD

**Issue by akashisama** [language-learners/phpbb#12]
[Version 1.1 of postlove has just been released](https://github.com/satanasov/postlove). Importantly it fixes the notification problem we've been having.

This will be the first time an extension's been updated on the forum right? According to [this](https://www.phpbb.com/extensions/installing/#updating) you should disable the extension before updating the files.

To update the files you just need to run "git fetch" in /phpBB/ext/anavaro/postlove/ I think. Then enable postlove again in the ACP.

-AlexTG

**Comment by emk** [comment]
Thank you, @akashisama! I'm sorry it took me so long to get caught back up with forum patches, but your bug report was extremely helpful, and thank you for reminding me to disable the extension before uploading. :-) We're now running version 1.1.1.
