### ISSUE TITLE
Move to dedicated AWS account

### ISSUE THREAD

**Issue by emk** [language-learners/phpbb#15]
Our apologies for the (scheduled) downtime!

Right now, the forum is running on my personal AWS account, after last week's late night emergency migration. This has three major problems:

- It's hard to grant administrative access to other people.
- There's no way to see what the forum actually costs to run, because forum billing is mixed in with billing for my personal sites.
- The emergency setup cut a lot of corners that we want to fix before living with them forever. :-)

In the interests of maintainability and transparency, we're moving the forum to a dedicated AWS account.

## Step needed to complete the switchover

- [x] [Set up Terrraform](https://github.com/language-learners/terraform) for the new account.
- [x] Configure new GitHub → [ECS](https://aws.amazon.com/ecs/) deployment pipelines, allowing us to deploy new forum versions by committing changes to GitHub and clicking a single "Approve" button.
- [x] Configure a new database server and EBS volume (for image uploads, etc.) on the new AWS account.
- [x] Configure a new server which automatically applies security updates, attaches the EBS volume and registers itself with ECS on startup.
- [x] Set up Route53 DNS records on the new AWS account.
- [x] Point the domain at the new Route53 DNS setup.
- [x] Put the _current_ site into "maintenance" mode, with a message pointing here.
- [x] Copy over the database(s), making sure to convert them from MyISAM to InnoDB (#16), so that backups will actually work reliably. We like backups.
- [x] Copy over the files.
- [x] **New:** Deal with bizarre DNS issue. Of course.
- [x] **ARGGGH!** Git submodules and CodePipeline don't play nicely! Oh, yuck. [The terrible evil things I do for this forum](https://github.com/language-learners/phpbb/commit/fa6c71ff499198a243e834183cfcdaf244a65b13).
- [x] Restart the `phpbb` container.
- [x] Test the site on a test domain.
- [x] Turn off maintenance mode on the _new_ site.
- [x] Fix failure to see forum data volume after reboot.
- [x] Update various DNS records.
- [x] Update announcement on old site to tell people their DNS is stale and they may need to wait a bit or reboot.

**We're back online!** If you're still seeing the old forum with the message about maintenance, your DNS records are out of date. Try the following:

1. Restart your browser.
2. Reboot your computer.
3. Wait from an hour to 2 days, depending on how awful your ISP's DNS cache is. It shouldn't take more than 5 minutes for you to see the new site, but some DNS servers are badly configured.

Once this is done, we can work on:

- The blog (#22).
- A Docker-aware reverse proxy so we can easily host multiple subdomains on a single server without paying $21/month for a load balancer (#20).
- Get the SuperChallenge bot back online (#21).

**Comment by rdearman** [comment]
Might want to think about having a dedicated email server as a docker app. 
https://github.com/tomav/docker-mailserver

**Comment by emk** [comment]
Good idea! Let's discuss that under issue #17.

**Comment by emk** [comment]
Sigh. My testing wasn't as good as I thought it was. We really need a "staging" environment, a server which looks just like the real one, and which allows us to test everything in a real environment before users see it.

Anyway, I am currently dealing with [horrors that humankind was never meant to know](https://github.com/language-learners/phpbb/commit/fa6c71ff499198a243e834183cfcdaf244a65b13) (subtype: terrible things done with git plumbing commands in the middle of a migration that didn't go as planned).

**Comment by emk** [comment]
And we're back! Yay!
